server:
  port: 8183

spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: localhost:9092
    topic:
      name: user-events
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "io.gsc.model.event"
        spring.json.value.default.type: "io.gsc.model.event.UserEvent"

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: 12a4f88b589b69
    password: 7801c0bcd246d2
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    root: info
    io.gsc: debug